### ISSUE TITLE
Shorten user facing script / add modularity ? 

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.ensemblemd#46]
Does the user facing script really need to be so long ? Example functions like perform_swap() can be imported from another file (temp_exch.py ?), similarly for exchange(), weighted_choice_sub(), etc. Is it possible (/does it make sense) to minimize the user facing script by keeping only the functions which require user input ?

**Comment by AntonsT** [comment]
>Does the user facing script really need to be so long ?

Long is a relative measure.

>Example functions like perform_swap() can be imported from another file (temp_exch.py ?),

Sure it can but why? Can you explain why a method having a total of 5 lines of code should be placed in another file?

>Is it possible (/does it make sense) to minimize the user facing script by keeping only the functions which require user input ?

Why perform_swap(), exchange() and weighted_choice_sub() don't require user input? perform_swap() for example is re algorithm dependant and should be implemented by enmd application developer. Similarly implementation of exchange() may vary depending on underlying re algorithm, for example in 2d RE replicas are grouped based on parameters in each dimension and enmd application developer knows that and should provide implementation.  
In principle, in a feature complete enmd application for replica exchange, routines specific to exchange procedure should indeed be placed in a separate module and replaced by imports and function calls so that developer can plug-in needed exchange scheme, but we are not at that stage yet.

**Comment by vivek-bala** [comment]
I didn't mean just those few lines but functions specific to temperature exchange. But as you said, this is to be in the future.
