### ISSUE TITLE
Questions for the Profiling Utility

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.ensemblemd#62]
Trying to integrate the profiling utility some questions have risen, especially after the discussion I had with Mark.
The logentry of the CUs, I think, has changed significantly between what exists in the master and devel of RP. The message "All FTW output staging directives done" and the logentry attribute of the unit's logentry I think it does not exist in the devel of RP. If I am mistaken somewhere, please correct me.

Assuming that the above observations are correct, I have a couple of questions.

1) Should EnsembleMD know about the logentry of a CU, in the sense of using it to perform some work with it?
2) Is it correct to use the messages that exist in the logentry as checks to get our timings? Should it be better if we used something more generic like CU states? I understand that the timestamp of each CU state exists in the logentry.

**Comment by marksantcroos** [comment]
Aren't these the same questions?

In general I would say the answer is: No, these are free text strings.

You are probably more interested in the state_history entry.

**Comment by iparask** [comment]
The second question assumes that the first is answered positively. Otherwise, if we should not use the unit's logentry attribute, there is a need for a different method to profile Ensemble MD runs

**Comment by marksantcroos** [comment]
I tried to suggest that in the latter part of my message.

**Comment by andre-merzky** [comment]
log messages in RP devel are indeed different from master.  In general, just as Mark said, log messages are unspecified  strings, and Ole only reverted to use them because the information was not available otherwise.  The same information should, however, now be available as state transitions, so it should be possible to adapt the code to look at the states (as it does elsewhere anyway).

**Comment by oleweidner** [comment]
Since we neither have a stable version of RADICL-Pilot ‘devel', nor a confirmed release date, I strongly suggest to stick what’s currently available in the latest radical-pilot release (0.23).

In the interest of productivity, I would like to advise EnsembleMD developers to STICK TO THE CURRENT RELEASE and not to work with RP ‘devel' yet. This would inevitably bring things to a grinding halt at this stage of development.

Having said that, it would of course make sense to isolate any code that is potentially affected by future changes in RP, so a smooth transition / migration to the new release can be guaranteed. During that transition time, we can install and use EnsembleMD with 0.23 from PyPi until support for 0.24 (?) has been fully implemented. This way there will be no transition-specific "down-time". 

Ioannis, with your initial question, you are probably referring to the implementation of event time gathering in EnsemblemMD [1]. While this is by no means prefect, it works reliably with Radical-Pilot 0.23. Andre came to the same conclusion after reviewing the code. Unless there are further concerns, you can probably just use this code in your execution plug-in? 


[1] https://github.com/radical-cybertools/radical.ensemblemd/blob/devel/src/radical/ensemblemd/utils.py

**Comment by iparask** [comment]
I am referring to lines 43-48 of the script. Unfortunately, it can not run for my execution plugin and the reason is here [1]. I want to use the same code. There is no reason to have different profiling methodology between execution plugins. A quick around is to take the rest of the code and include it in my execution plugin and do the profiling from there, but I do not think it is a good idea since it over complicates things without any reason

[1] https://github.com/radical-cybertools/radical.pilot/issues/501

**Comment by oleweidner** [comment]
Ah, I see now. One thing I get from #501 is that it works if you use list of values or just one dictionary. Would it be possible to change the staging code in your execution plugin slightly in order to make it work? 

Depending on the RP 'devel' branch / the 0.24 release of RP at this point of time would be disruptive. I think our goal should be to make EnMD work with RP 0.23.

**Comment by iparask** [comment]
Exactly. It works only if you use a list of values or just one dictionary. 
I am not so sure... 
I could give it a try and use the default values of the pilot's staging to reduce everything to a list but It would result to duplicating many times the same files for sure. 

Can you explain me what the log messages you are using mean? I may be able to devise a workaround.

**Comment by oleweidner** [comment]
That's not entirely clear to me either - I extracted them in a trial and error-based fashion myself as you can easily by the absurd combination of .log and .state_history. 

Which log messages in particular are you interested in?

**Comment by iparask** [comment]
The "All FTW Input Staging Directives done" and "All FTW output staging directives done". That is the only part that causes a problem with my implementation. I also think that if understand what they are for I may be able to create a workaround from my execution plugin.

**Comment by oleweidner** [comment]
Ah. So "All FTW Input Staging Directives done" (no idea what "FTW" stands for) marks the point in time where the manager has finished all input staging. I relied on this value because in the state history this is doesn't become entirely clear. Same story for the "All FTW output staging directives done". At in my memory, this was the case 

Looking at the following output, it seems that we can replace these two with ``PendingExecution`` and ``Done`` respectively. That should be close enough. I will implement this in devel now - it would be great if you could give it a try in a few minutes. 

```
    for unit in units:
        for hist in unit.state_history:
            print ("{0} - {1}".format(hist.timestamp, hist.state))

        for l in unit.log:
            print ("{0} - {1}".format(l.timestamp, l.logentry))
```

```
2015-03-20 17:12:38.720000 - New
2015-03-20 17:13:07.040000 - StagingInput
2015-03-20 17:13:09.128000 - PendingExecution
2015-03-20 17:13:09.250000 - Scheduling
2015-03-20 17:13:09.374000 - Executing
2015-03-20 17:13:09.666000 - StagingOutput
2015-03-20 17:13:09.760000 - StagingOutput
2015-03-20 17:13:11.417000 - Done


2015-03-20 17:12:38.944000 - unit remains unscheduled
2015-03-20 17:13:06.699000 - Scheduled for data transfer to ComputePilot 550c55056bf88b1978e14824.
2015-03-20 17:13:08.185000 - Transferring input file file://localhost//Users/oweidner/Projects/radical.pilot/file1.dat -> file://localhost/Users/oweidner/radical.pilot.sandbox/pilot-550c55056bf88b1978e14824//unit-550c55066bf88b1978e14826/file1.dat
2015-03-20 17:13:08.768000 - Transferring input file file://localhost//Users/oweidner/Projects/radical.pilot/file2.dat -> file://localhost/Users/oweidner/radical.pilot.sandbox/pilot-550c55056bf88b1978e14824//unit-550c55066bf88b1978e14826/file2.dat
2015-03-20 17:13:09.016000 - All FTW Input Staging Directives done - 1.
2015-03-20 17:13:09.929000 - Starting transfer of file1.dat
2015-03-20 17:13:10.390000 - Transferring output file file://localhost/Users/oweidner/radical.pilot.sandbox/pilot-550c55056bf88b1978e14824//unit-550c55066bf88b1978e14826/file1.dat -> file://localhost/Users/oweidner/Projects/radical.pilot/file1.dat
2015-03-20 17:13:10.655000 - Starting transfer of file2.dat
2015-03-20 17:13:11.150000 - Transferring output file file://localhost/Users/oweidner/radical.pilot.sandbox/pilot-550c55056bf88b1978e14824//unit-550c55066bf88b1978e14826/file2.dat -> file://localhost/Users/oweidner/Projects/radical.pilot/file2.dat
2015-03-20 17:13:11.289000 - All FTW output staging directives done - 1.
[Callback]: ComputePilot '550c55056bf88b1978e14824' state: Canceled.
```

**Comment by iparask** [comment]
Just tell me when!

**Comment by oleweidner** [comment]
Now :-) Please check out the latest `devel` branch.

For me the output looks ok 

```
0   simulation_iteration_1   pattern_step 2015-03-20 18:18:40.570198   
1   simulation_iteration_1   data_stagein 2015-03-20 17:18:53.623000   
2   simulation_iteration_1      execution 2015-03-20 17:18:57.200000   
3   simulation_iteration_1  data_stageout 2015-03-20 17:19:07.324000   
4     analysis_iteration_1   pattern_step 2015-03-20 18:20:35.951854   
5     analysis_iteration_1   data_stagein 2015-03-20 17:20:46.845000   
6     analysis_iteration_1      execution 2015-03-20 17:20:49.122000   
7     analysis_iteration_1  data_stageout 2015-03-20 17:20:59.323000   
8   simulation_iteration_2   pattern_step 2015-03-20 18:22:26.761440   
9   simulation_iteration_2   data_stagein 2015-03-20 17:22:37.685000   
10  simulation_iteration_2      execution 2015-03-20 17:22:39.648000   
11  simulation_iteration_2  data_stageout 2015-03-20 17:22:49.812000   

```

**Comment by iparask** [comment]
I think now I can close it.

**Comment by oleweidner** [comment]
Excellent. Cheers!

**Comment by marksantcroos** [comment]
> (no idea what "FTW" stands for)

File Transfer Worker
