### ISSUE TITLE
Cluster Deallocation

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.ensemblemd#64]
Since the cluster allocation is done in the user script, shouldn't for consistency at least the deallocation of the cluster's resources happen also in the user's script and if an exception happens before the script has finished to de-allocate the resources in a similar way as we do now?

**Comment by oleweidner** [comment]
Good point. Obviously, one could also argue that an implicit deallocation happens when the object(s) go out of scope. But that's a matter of taste really. 

But given the rather goofy garbage collection in Python, I have no objections agains a `deallocate` method, as it would give us more explicit control. 

Can you implement a `deallocate` method?

**Comment by iparask** [comment]
Yes, I will do it!

**Comment by oleweidner** [comment]
Great, thanks!

**Comment by iparask** [comment]
I pushed a new branch for the deallocate method. It is only supported in the all-pairs pattern.

The tests I run are run the all_pairs example locally and on Stampede and Ctrl+C them. It deallocates the cluster. Also I introduced errors and the cluster is freed and report the traceback of the error.

Feel free to test it. I will implement it to the rest of the patterns.

**Comment by iparask** [comment]
Closing ticket. Branch to be merged with devel
